ProgramInfo:
  program_name: web - Mirror-Elf by TG@seo898
  authorization_code: LJ2jwuZCDs1gjj2aGZ-B0p_LwsQ3aIEqcbgdRO2lz_AunMoPJUnbVT17Yh0uM3cUNIUhIILXwG8B19dDDGfF-BjqHB62
  login_account: admin
  login_password: admin
  pg_database_url: postgresql://admin:mirrorelf@localhost:5432/mirror
WebsiteSettings:
  auto_site_building: true
  auto_https_certificate: false
  pan_site_auto_site_building: false
  pan_site_crawler_target: true
  language: zh
  link_mapping: true
  homepage_update_time: 3
  target_static_save: .js,.css,.jpg,.png
SEOFunctions:
  external_filter:
  - .gov.cn
  external_links:
  - '{随机网址}'
  meta_information: true
  random_div_attributes: true
  random_class_name: true
  head_header: ''
  head_footer: ''
  body_header: <h1><a target="_blank" title="{标题}" href="{首页}">{核心词}</a></h1>
  body_footer: |-
    <a target="_blank" href="{@push_link}">{@keyword}</a>
    <a target="_blank" href="{@push_link}">{@keyword}</a>
    <a target="_blank" href="{@push_link}">{@keyword}</a>
    <a target="_blank" href="{@push_link}">{@keyword}</a>
    <a target="_blank" href="{@push_link}">{@keyword}</a>
  html_entities: true
  friend_link_count: 5
  friend_links:
  - <a target="_blank" title="{*主站.标题#1001}" href="{*主站.首页#1001}">{*主站.核心词#1001}</a>
  seo_404_page: true
AccessPolicy:
  forced_domain_binding: false
  ip_site_referrer: true
  pan_site_referrer: true
  ua_banlist:
  - HttpClient
  - UniversalFeedParser
  - lightDeckReports Bot
  - heritrix
  - Java
  - Bytespider
  - YandexBot
  - FlightDeckReports
  - Indy Library
  - BOT/0.1
  - DigExt
  - Feedly
  - Swiftbot
  - oBot
  - Python-urllib
  - CrawlDaddy
  - YYSpider
  - JikeSpider
  - ZmEu
  - MJ12bot
  - WebZIP
  - Apache-HttpAsyncClient
  - HttpClient
  - WinHttp
  - jaunty
  - Alexa Toolbar
  - LinkpadBot
  - Microsoft URL Control
  - node-superagent
  - Ezooms
  - Jullo
  - SemrushBot
  - FetchURL
  - AhrefsBot
  - EasouSpider
  - java/
  - CoolpadWebkit
  - Linguee Bot
  ip_banlist: []
AdPolicy:
  ad_url: http://www.baidu.com
  search_referrer_jump_ad: false
  regular_ua_jump_ad: false
GlobalCodeInsertion:
  filter_ip:
  - 156.59.82.*
  head_header: <script src="/_/static/js/ad1.js" type="text/javascript"></script>
  head_footer: ''
  body_header: ''
  body_footer: ''
SpiderPolicy:
  baidu_spider: true
  sogou_spider: true
  yisou_spider: true
  byte_spider: true
  bing_spider: true
  so_spider: true
  google_img_spider: true
  google_spider: true
  quark_spider: true
  yahoo_spider: true
  other_spider: true
  user: true
