services:
  mirror_elf_r:
    network_mode: host
    restart: always
    build: ./app
    container_name: mirror_elf_r
    volumes:
      - ./app:/app
  ############ PostgreSQL 服务配置 ############
  ############ 使用以下命令可在本地运行 PostgreSQL 容器 ############
  # docker run --name my-postgres \
  #   -e POSTGRES_USER=admin \
  #   -e POSTGRES_PASSWORD=mirrorelf \
  #   -e POSTGRES_DB=mirror \
  #   -p 5432:5432 \
  #   -v pgdata:/var/lib/postgresql/data \
  #   -d postgres:16
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mirrorelf
      POSTGRES_DB: mirror
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "max_connections=4096"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
volumes:
  postgres_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /www/MirrorElf/pgsql_data  # 指定外部的路径
